using MappingSPO.Entities;

namespace MappingSPO
{
    public interface IXrmContext : System.IDisposable
    {
        System.Data.Entity.DbSet<ActiviteitenEntity> Activiteitens { get; set; }
        System.Data.Entity.DbSet<ActiviteitGpsLinkDataEntity> ActiviteitGpsLinkDatas { get; set; }
        System.Data.Entity.DbSet<ActiviteitGroupEntity> ActiviteitGroups { get; set; }
        System.Data.Entity.DbSet<AddinEntity> Addins { get; set; }
        System.Data.Entity.DbSet<AddinContractEntity> AddinContracts { get; set; }
        System.Data.Entity.DbSet<AddinContractsSecurityEntity> AddinContractsSecurities { get; set; }
        System.Data.Entity.DbSet<AfdelingEntity> Afdelings { get; set; }
        System.Data.Entity.DbSet<AfmeldingPuntTypeEntity> AfmeldingPuntTypes { get; set; }
        System.Data.Entity.DbSet<AfmeldingsPuntenEntity> AfmeldingsPuntens { get; set; }
        System.Data.Entity.DbSet<AfmeldingspuntenGpsLinkDataEntity> AfmeldingspuntenGpsLinkDatas { get; set; }
        System.Data.Entity.DbSet<ArticleDefaultEntity> ArticleDefaults { get; set; }
        System.Data.Entity.DbSet<AutomaticCalcLibraryEntity> AutomaticCalcLibraries { get; set; }
        System.Data.Entity.DbSet<AutomaticCalcSettingEntity> AutomaticCalcSettings { get; set; }
        System.Data.Entity.DbSet<BAnaCodeEntity> BAnaCodes { get; set; }
        System.Data.Entity.DbSet<BAnaGroup1Entity> BAnaGroup1 { get; set; }
        System.Data.Entity.DbSet<BAnaSubGroupEntity> BAnaSubGroups { get; set; }
        System.Data.Entity.DbSet<BatchJobEntity> BatchJobs { get; set; }
        System.Data.Entity.DbSet<BatchJobParameterEntity> BatchJobParameters { get; set; }
        System.Data.Entity.DbSet<BatchServiceSettingEntity> BatchServiceSettings { get; set; }
        System.Data.Entity.DbSet<BetaalWijzeEntity> BetaalWijzes { get; set; }
        System.Data.Entity.DbSet<BoekPeriodeEntity> BoekPeriodes { get; set; }
        System.Data.Entity.DbSet<BtwBoekingsgroepEntity> BtwBoekingsgroeps { get; set; }
        System.Data.Entity.DbSet<CalcCode1Entity> CalcCode1 { get; set; }
        System.Data.Entity.DbSet<CalcCode2Entity> CalcCode2 { get; set; }
        System.Data.Entity.DbSet<CalcCode3Entity> CalcCode3 { get; set; }
        System.Data.Entity.DbSet<CalcCode4Entity> CalcCode4 { get; set; }
        System.Data.Entity.DbSet<CalcCode5Entity> CalcCode5 { get; set; }
        System.Data.Entity.DbSet<CalcCode6Entity> CalcCode6 { get; set; }
        System.Data.Entity.DbSet<CalcCode7Entity> CalcCode7 { get; set; }
        System.Data.Entity.DbSet<CalcCode8Entity> CalcCode8 { get; set; }
        System.Data.Entity.DbSet<CalcErrorEntity> CalcErrors { get; set; }
        System.Data.Entity.DbSet<CalcFilterEntity> CalcFilters { get; set; }
        System.Data.Entity.DbSet<CalcLineTypeEntity> CalcLineTypes { get; set; }
        System.Data.Entity.DbSet<CalcTypeEntity> CalcTypes { get; set; }
        System.Data.Entity.DbSet<CashDiscountEntity> CashDiscounts { get; set; }
        System.Data.Entity.DbSet<CategoryEntity> Categories { get; set; }
        System.Data.Entity.DbSet<CityEntity> Cities { get; set; }
        System.Data.Entity.DbSet<ClientDiscountEntity> ClientDiscounts { get; set; }
        System.Data.Entity.DbSet<CodaBoxSettingEntity> CodaBoxSettings { get; set; }
        System.Data.Entity.DbSet<CodeEntity> Codes { get; set; }
        System.Data.Entity.DbSet<CodeCaptionTranslationEntity> CodeCaptionTranslations { get; set; }
        System.Data.Entity.DbSet<CodeTranslationEntity> CodeTranslations { get; set; }
        System.Data.Entity.DbSet<CompanyEntity> Companies { get; set; }
        System.Data.Entity.DbSet<CompanyRekeningenEntity> CompanyRekeningens { get; set; }
        System.Data.Entity.DbSet<CompanyUserGroepRightEntity> CompanyUserGroepRights { get; set; }
        System.Data.Entity.DbSet<CompanyUserRightEntity> CompanyUserRights { get; set; }
        System.Data.Entity.DbSet<ContactCodeEntity> ContactCodes { get; set; }
        System.Data.Entity.DbSet<ContactsMultiAnaCodeEntity> ContactsMultiAnaCodes { get; set; }
        System.Data.Entity.DbSet<ContactTypeEntity> ContactTypes { get; set; }
        System.Data.Entity.DbSet<CostHeaderTypeEntity> CostHeaderTypes { get; set; }
        System.Data.Entity.DbSet<CounterDefinitionEntity> CounterDefinitions { get; set; }
        System.Data.Entity.DbSet<CounterWerkCodeEntity> CounterWerkCodes { get; set; }
        System.Data.Entity.DbSet<CountriesLinkDataEntity> CountriesLinkDatas { get; set; }
        System.Data.Entity.DbSet<CountryEntity> Countries { get; set; }
        System.Data.Entity.DbSet<CountryLanguageEntity> CountryLanguages { get; set; }
        System.Data.Entity.DbSet<CurrencyEntity> Currencies { get; set; }
        System.Data.Entity.DbSet<DagZoneEntity> DagZones { get; set; }
        System.Data.Entity.DbSet<DocCode1Entity> DocCode1 { get; set; }
        System.Data.Entity.DbSet<DocCode2Entity> DocCode2 { get; set; }
        System.Data.Entity.DbSet<DocCode3Entity> DocCode3 { get; set; }
        System.Data.Entity.DbSet<DocCode4Entity> DocCode4 { get; set; }
        System.Data.Entity.DbSet<DocumentEntity> Documents { get; set; }
        System.Data.Entity.DbSet<DocumentTypeEntity> DocumentTypes { get; set; }
        System.Data.Entity.DbSet<DynAx2012CustSettingsEntity> DynAx2012CustSettings { get; set; }
        System.Data.Entity.DbSet<EmailTypeEntity> EmailTypes { get; set; }
        System.Data.Entity.DbSet<EmailTypeTextEntity> EmailTypeTexts { get; set; }
        System.Data.Entity.DbSet<EmmaAddinEntity> EmmaAddins { get; set; }
        System.Data.Entity.DbSet<EmmaAddinContractEntity> EmmaAddinContracts { get; set; }
        System.Data.Entity.DbSet<EmmaAddinContractsSecurityEntity> EmmaAddinContractsSecurities { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode1Entity> EmmaAnaCode1 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode2Entity> EmmaAnaCode2 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode3Entity> EmmaAnaCode3 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode4Entity> EmmaAnaCode4 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode5Entity> EmmaAnaCode5 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode6Entity> EmmaAnaCode6 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode7Entity> EmmaAnaCode7 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode8Entity> EmmaAnaCode8 { get; set; }
        System.Data.Entity.DbSet<EmmaAnaCode9Entity> EmmaAnaCode9 { get; set; }
        System.Data.Entity.DbSet<EmmaMagazijnEntity> EmmaMagazijns { get; set; }
        System.Data.Entity.DbSet<EmmaOfferLabelValueEntity> EmmaOfferLabelValues { get; set; }
        System.Data.Entity.DbSet<EmmaOfferTypeEntity> EmmaOfferTypes { get; set; }
        System.Data.Entity.DbSet<EmmaTextenEntity> EmmaTextens { get; set; }
        System.Data.Entity.DbSet<EmmaTextGroupEntity> EmmaTextGroups { get; set; }
        System.Data.Entity.DbSet<EmmaUserSettingEntity> EmmaUserSettings { get; set; }
        System.Data.Entity.DbSet<EmmaVerzendwijzeEntity> EmmaVerzendwijzes { get; set; }
        System.Data.Entity.DbSet<EmmaVkoTypeEntity> EmmaVkoTypes { get; set; }
        System.Data.Entity.DbSet<ExactOnlineSettingEntity> ExactOnlineSettings { get; set; }
        System.Data.Entity.DbSet<ExportVatSettingEntity> ExportVatSettings { get; set; }
        System.Data.Entity.DbSet<ExternalApiSettingEntity> ExternalApiSettings { get; set; }
        System.Data.Entity.DbSet<ExternalDatabaseEntity> ExternalDatabases { get; set; }
        System.Data.Entity.DbSet<ExternalInvoiceBuildSettingEntity> ExternalInvoiceBuildSettings { get; set; }
        System.Data.Entity.DbSet<ExternalInvoiceUserSettingEntity> ExternalInvoiceUserSettings { get; set; }
        System.Data.Entity.DbSet<HcEntity> Hcs { get; set; }
        System.Data.Entity.DbSet<HerzieningIndexEntity> HerzieningIndexes { get; set; }
        System.Data.Entity.DbSet<HerzieningTemplateEntity> HerzieningTemplates { get; set; }
        System.Data.Entity.DbSet<HerzieningTemplateTermEntity> HerzieningTemplateTerms { get; set; }
        System.Data.Entity.DbSet<IncomingInvoiceSettingEntity> IncomingInvoiceSettings { get; set; }
        System.Data.Entity.DbSet<InvoiceEntity> Invoices { get; set; }
        System.Data.Entity.DbSet<InvoiceExportEntity> InvoiceExports { get; set; }
        System.Data.Entity.DbSet<InvoiceExportGeneralEntity> InvoiceExportGenerals { get; set; }
        System.Data.Entity.DbSet<InvoicePlanDefaultEntity> InvoicePlanDefaults { get; set; }
        System.Data.Entity.DbSet<InvoicePlanDefaultsSchijvenEntity> InvoicePlanDefaultsSchijvens { get; set; }
        System.Data.Entity.DbSet<KsEntity> Ks { get; set; }
        System.Data.Entity.DbSet<LanguageEntity> Languages { get; set; }
        System.Data.Entity.DbSet<MaatTypeEntity> MaatTypes { get; set; }
        System.Data.Entity.DbSet<MagazijnEntity> Magazijns { get; set; }
        System.Data.Entity.DbSet<MobiliteitsCodeEntity> MobiliteitsCodes { get; set; }
        System.Data.Entity.DbSet<MobiliteitsCodeTarievenEntity> MobiliteitsCodeTarievens { get; set; }
        System.Data.Entity.DbSet<MobiliteitTariefDetailEntity> MobiliteitTariefDetails { get; set; }
        System.Data.Entity.DbSet<OpmetingDefinitionEntity> OpmetingDefinitions { get; set; }
        System.Data.Entity.DbSet<ParitairComiteEntity> ParitairComites { get; set; }
        System.Data.Entity.DbSet<ParitairComiteCounterEntity> ParitairComiteCounters { get; set; }
        System.Data.Entity.DbSet<PayConditionEntity> PayConditions { get; set; }
        System.Data.Entity.DbSet<PlanningResourceEntity> PlanningResources { get; set; }
        System.Data.Entity.DbSet<PrijsAntwoordSoortEntity> PrijsAntwoordSoorts { get; set; }
        System.Data.Entity.DbSet<ProjectCode1Entity> ProjectCode1 { get; set; }
        System.Data.Entity.DbSet<ProjectCode2Entity> ProjectCode2 { get; set; }
        System.Data.Entity.DbSet<ProjectCode3Entity> ProjectCode3 { get; set; }
        System.Data.Entity.DbSet<ProjectCode4Entity> ProjectCode4 { get; set; }
        System.Data.Entity.DbSet<ProjectCode5Entity> ProjectCode5 { get; set; }
        System.Data.Entity.DbSet<ProjectCode6Entity> ProjectCode6 { get; set; }
        System.Data.Entity.DbSet<ProjectCode7Entity> ProjectCode7 { get; set; }
        System.Data.Entity.DbSet<ProjectCode8Entity> ProjectCode8 { get; set; }
        System.Data.Entity.DbSet<ProjectExplorerSpecialQueryEntity> ProjectExplorerSpecialQueries { get; set; }
        System.Data.Entity.DbSet<ProjectResultReasonEntity> ProjectResultReasons { get; set; }
        System.Data.Entity.DbSet<ProjectTypeEntity> ProjectTypes { get; set; }
        System.Data.Entity.DbSet<ProjectTypeUserEntity> ProjectTypeUsers { get; set; }
        System.Data.Entity.DbSet<ProjectTypeUserGroupEntity> ProjectTypeUserGroups { get; set; }
        System.Data.Entity.DbSet<ProjectTypeWorkFlowEntity> ProjectTypeWorkFlows { get; set; }
        System.Data.Entity.DbSet<ProjectUnitCodeEntity> ProjectUnitCodes { get; set; }
        System.Data.Entity.DbSet<ProjectUnitMultiAnaCodeEntity> ProjectUnitMultiAnaCodes { get; set; }
        System.Data.Entity.DbSet<ProjectUnitsSearchMapUserSettingEntity> ProjectUnitsSearchMapUserSettings { get; set; }
        System.Data.Entity.DbSet<QueriesDxEntity> QueriesDxes { get; set; }
        System.Data.Entity.DbSet<QueryEntity> Queries { get; set; }
        System.Data.Entity.DbSet<RegionEntity> Regions { get; set; }
        System.Data.Entity.DbSet<RekeningNrEntity> RekeningNrs { get; set; }
        System.Data.Entity.DbSet<RelActiviteitEntity> RelActiviteits { get; set; }
        System.Data.Entity.DbSet<RelActiviteitGroupEntity> RelActiviteitGroups { get; set; }
        System.Data.Entity.DbSet<RelationCode1Entity> RelationCode1 { get; set; }
        System.Data.Entity.DbSet<RelationCode2Entity> RelationCode2 { get; set; }
        System.Data.Entity.DbSet<RelationCode3Entity> RelationCode3 { get; set; }
        System.Data.Entity.DbSet<RelationCode4Entity> RelationCode4 { get; set; }
        System.Data.Entity.DbSet<RelationCode5Entity> RelationCode5 { get; set; }
        System.Data.Entity.DbSet<RelationCode6Entity> RelationCode6 { get; set; }
        System.Data.Entity.DbSet<RelationCode7Entity> RelationCode7 { get; set; }
        System.Data.Entity.DbSet<RelationCode8Entity> RelationCode8 { get; set; }
        System.Data.Entity.DbSet<RelationTypeEntity> RelationTypes { get; set; }
        System.Data.Entity.DbSet<RelOpportunityEntity> RelOpportunities { get; set; }
        System.Data.Entity.DbSet<RelOpportunityGroupEntity> RelOpportunityGroups { get; set; }
        System.Data.Entity.DbSet<ReportEntity> Reports { get; set; }
        System.Data.Entity.DbSet<ReportLayoutsDxEntity> ReportLayoutsDxes { get; set; }
        System.Data.Entity.DbSet<ReportsDxEntity> ReportsDxes { get; set; }
        System.Data.Entity.DbSet<ReportsDxFormLinkEntity> ReportsDxFormLinks { get; set; }
        System.Data.Entity.DbSet<SageBobCompanySettingEntity> SageBobCompanySettings { get; set; }
        System.Data.Entity.DbSet<SalesDefaultEntity> SalesDefaults { get; set; }
        System.Data.Entity.DbSet<SecurityRuleEntity> SecurityRules { get; set; }
        System.Data.Entity.DbSet<SettingEntity> Settings { get; set; }
        System.Data.Entity.DbSet<SubCategoryEntity> SubCategories { get; set; }
        System.Data.Entity.DbSet<SysCalculationParaEntity> SysCalculationParas { get; set; }
        System.Data.Entity.DbSet<SysMasterProjectSettingEntity> SysMasterProjectSettings { get; set; }
        System.Data.Entity.DbSet<SysMpSettingsCijferEntity> SysMpSettingsCijfers { get; set; }
        System.Data.Entity.DbSet<SysMpSettingsCijfersLabelEntity> SysMpSettingsCijfersLabels { get; set; }
        System.Data.Entity.DbSet<SysProjectSettingEntity> SysProjectSettings { get; set; }
        System.Data.Entity.DbSet<SysProjectUserSettingEntity> SysProjectUserSettings { get; set; }
        System.Data.Entity.DbSet<SysRelationsParaEntity> SysRelationsParas { get; set; }
        System.Data.Entity.DbSet<SysSalesInvoiceParaEntity> SysSalesInvoiceParas { get; set; }
        System.Data.Entity.DbSet<SysUserFilterEntity> SysUserFilters { get; set; }
        System.Data.Entity.DbSet<SysUserSettingObjectEntity> SysUserSettingObjects { get; set; }
        System.Data.Entity.DbSet<SysUserSettingUserObjectEntity> SysUserSettingUserObjects { get; set; }
        System.Data.Entity.DbSet<SysUserViewEntity> SysUserViews { get; set; }
        System.Data.Entity.DbSet<SysWerfParaEntity> SysWerfParas { get; set; }
        System.Data.Entity.DbSet<TeamsIntegrationEntity> TeamsIntegrations { get; set; }
        System.Data.Entity.DbSet<ToDoItemStateEntity> ToDoItemStates { get; set; }
        System.Data.Entity.DbSet<TodoTypeEntity> TodoTypes { get; set; }
        System.Data.Entity.DbSet<TodoTypeItemStateEntity> TodoTypeItemStates { get; set; }
        System.Data.Entity.DbSet<TofSettingEntity> TofSettings { get; set; }
        System.Data.Entity.DbSet<TransportMiddelEntity> TransportMiddels { get; set; }
        System.Data.Entity.DbSet<UcEntity> Ucs { get; set; }
        System.Data.Entity.DbSet<UcUcEntity> UcUcs { get; set; }
        System.Data.Entity.DbSet<UnitTypeEntity> UnitTypes { get; set; }
        System.Data.Entity.DbSet<UserEntity> Users { get; set; }
        System.Data.Entity.DbSet<UsersGroepEntity> UsersGroeps { get; set; }
        System.Data.Entity.DbSet<VatEntity> Vats { get; set; }
        System.Data.Entity.DbSet<VatRegimeEntity> VatRegimes { get; set; }
        System.Data.Entity.DbSet<VatRegimeNoteEntity> VatRegimeNotes { get; set; }
        System.Data.Entity.DbSet<VeniceSettingEntity> VeniceSettings { get; set; }
        System.Data.Entity.DbSet<WerfCode1Entity> WerfCode1 { get; set; }
        System.Data.Entity.DbSet<WerfCode2Entity> WerfCode2 { get; set; }
        System.Data.Entity.DbSet<WerfCode3Entity> WerfCode3 { get; set; }
        System.Data.Entity.DbSet<WerfCode4Entity> WerfCode4 { get; set; }
        System.Data.Entity.DbSet<WerfCode5Entity> WerfCode5 { get; set; }
        System.Data.Entity.DbSet<WerfCode6Entity> WerfCode6 { get; set; }
        System.Data.Entity.DbSet<WerfCode7Entity> WerfCode7 { get; set; }
        System.Data.Entity.DbSet<WerfCode8Entity> WerfCode8 { get; set; }
        System.Data.Entity.DbSet<WerfDocSearchMapUserSettingEntity> WerfDocSearchMapUserSettings { get; set; }
        System.Data.Entity.DbSet<WerfMultiAnaCodeEntity> WerfMultiAnaCodes { get; set; }
        System.Data.Entity.DbSet<WerfPropertiesItemEntity> WerfPropertiesItems { get; set; }
        System.Data.Entity.DbSet<WerfTypeEntity> WerfTypes { get; set; }
        System.Data.Entity.DbSet<WerkCodeEntity> WerkCodes { get; set; }
        System.Data.Entity.DbSet<WholesalerEntity> Wholesalers { get; set; }
        System.Data.Entity.DbSet<WholesalerUnitcodeEntity> WholesalerUnitcodes { get; set; }
        System.Data.Entity.DbSet<WholesalerUserEntity> WholesalerUsers { get; set; }
        System.Data.Entity.DbSet<WinbookEntity> Winbooks { get; set; }
        System.Data.Entity.DbSet<WinbooksBoekYearPeriodToBoekingDatumEntity> WinbooksBoekYearPeriodToBoekingDatums { get; set; }
        System.Data.Entity.DbSet<WinbooksCompanyEntity> WinbooksCompanies { get; set; }
        System.Data.Entity.DbSet<WinbooksCompanyTableEntity> WinbooksCompanyTables { get; set; }
        System.Data.Entity.DbSet<WinbooksSettingEntity> WinbooksSettings { get; set; }
        System.Data.Entity.DbSet<WingsSettingEntity> WingsSettings { get; set; }
        System.Data.Entity.DbSet<WorkerContractTypeEntity> WorkerContractTypes { get; set; }
        System.Data.Entity.DbSet<WorkFlowEntity> WorkFlows { get; set; }
        System.Data.Entity.DbSet<WorkOrderTimeItemsCounterEntity> WorkOrderTimeItemsCounters { get; set; }
        System.Data.Entity.DbSet<WorkOrderTypeEntity> WorkOrderTypes { get; set; }
        System.Data.Entity.DbSet<WorkOrderTypeAfdelingEntity> WorkOrderTypeAfdelings { get; set; }
        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }
}
